name: Publish Docker Image

on:
  push:
    branches:
      - main
      - stage
      - dev

jobs:
  call-template:
    uses: microservices-final-project/ci-templates/.github/workflows/build.yml@main
    with:
      image_name: ${GITHUB_REPOSITORY##*/}
      image_tag: ${{ github.ref_name }}
      dockerfile_path: ./Dockerfile
      context: .
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      ACR_NAME: ${{ secrets.ACR_NAME }}
